### ISSUE TITLE
I look forward to leveraging my extensive experience and knowledge to contribute to your team’s goals and achievements.

### ISSUE THREAD

**Issue by johnsmith0212** [ohkami-rs/ohkami#217]
Hello, I'm Ethan Tan, a web full-stack and blockchain developer with more than 8 years in the field. I focus on building reliable, scalable web applications and advanced blockchain solutions. Leveraging my knowledge of React.js, Vue.js, and Next.js, combined with my Solidity skills for smart contract development, I provide high-quality, secure, and efficient solutions tailored to your distinct needs.

**Comment by kana-rus** [comment]
Thank you for your interest in Ohkami, Ethan. Your skills in web dev and blockchain are impressive.
Currently, building a formal team is just a future plan, but we welcome contributions through PRs and issues. Feel free to open issues or fork & submit pull requests!

**Comment by johnsmith0212** [comment]
okay
